/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/facilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Facilities
         * @description Return all facilities with their latest EVS score.
         *     Powers the map markers on the frontend dashboard.
         *     ADR-002: loaded from data/processed/facilities.parquet + evs_scores.parquet.
         */
        get: operations["list_facilities_facilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facilities/{facility_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Facility Detail
         * @description Full EVS detail for one facility — satellite estimate, reported value,
         *     discrepancy score.
         *     ADR-002: loaded from data/processed/evs_scores.parquet.
         */
        get: operations["get_facility_detail_facilities__facility_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Report
         * @description Trigger Granite report generation for a facility.
         *     Returns task_id immediately — poll GET /tasks/{task_id} for result.
         *     ADR-001: never blocks on Granite call.
         *     ADR-006: if GRANITE_MODE=cached, task completes instantly from cache.
         */
        post: operations["generate_report_reports_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description Fetch a previously generated report by ID.
         */
        get: operations["get_report_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/esg/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Esg Pdf
         * @description Accept a corporate ESG PDF and dispatch Granite parsing as a background task.
         *     Returns task_id — poll GET /tasks/{task_id} for the parsed ESGParseResult.
         *     Demo: task completes immediately from cache when GRANITE_MODE=cached (ADR-006).
         */
        post: operations["upload_esg_pdf_esg_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Status
         * @description Poll this endpoint to track progress of a background task.
         *     The `progress_stage` field drives the step-by-step indicator in the demo UI.
         */
        get: operations["get_task_status_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plume/{facility_id}/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plume Geojson
         * @description Returns a GeoJSON point collection for the Deck.gl HeatmapLayer.
         *     ADR-005: consumed by FacilityMap HeatmapLayer.
         *     In deterministic demo mode, returns an explicitly labelled synthetic
         *     overlay based on the committed fixture score.  Real satellite-processing
         *     mode will replace it with a cached raster-derived GeoJSON collection.
         */
        get: operations["get_plume_geojson_plume__facility_id__geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prototype/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Prototype Status
         * @description Return live-prototype readiness for the presentation dashboard.
         */
        get: operations["get_prototype_status_prototype_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verification/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Verification Run
         * @description Start a live Sentinel/ERA5/ML scoring pipeline run.
         */
        post: operations["start_verification_run_verification_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_esg_pdf_esg_upload_post */
        Body_upload_esg_pdf_esg_upload_post: {
            /** File */
            file: string;
        };
        /** CredentialStatus */
        CredentialStatus: {
            /** Copernicus */
            copernicus: boolean;
            /** Cds */
            cds: boolean;
            /** Watsonx */
            watsonx: boolean;
            /** Openpages */
            openpages: boolean;
            /** Fabric */
            fabric: boolean;
        };
        /** DataAvailability */
        DataAvailability: {
            /** Facilities File */
            facilities_file: boolean;
            /** Evs Scores File */
            evs_scores_file: boolean;
            /** Sentinel Raw Count */
            sentinel_raw_count: number;
            /** Era5 Raw Count */
            era5_raw_count: number;
            /** Processed Plume Count */
            processed_plume_count: number;
            /** Upload Count */
            upload_count: number;
            /** Audit Anchor Count */
            audit_anchor_count: number;
            /** Audit Case Count */
            audit_case_count: number;
        };
        /**
         * DiscrepancyFlag
         * @enum {string}
         */
        DiscrepancyFlag: "clear" | "watch" | "high";
        /** ESGUploadResponse */
        ESGUploadResponse: {
            /** Task Id */
            task_id: string;
            /** Filename */
            filename: string;
            /**
             * Status
             * @default processing
             */
            status: string;
        };
        /**
         * EVSScore
         * @description Core Emission Verification Score object.
         *     All CH4 values are in tonnes/year unless noted.
         */
        EVSScore: {
            /**
             * Facility Id
             * @description EU ETS or EPA GHGRP facility identifier
             */
            facility_id: string;
            /** Facility Name */
            facility_name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Observation Start
             * Format: date
             */
            observation_start: string;
            /**
             * Observation End
             * Format: date
             */
            observation_end: string;
            /**
             * Days With Valid Retrievals
             * @description Days in window with QA-passing TROPOMI data
             */
            days_with_valid_retrievals: number;
            /**
             * Coverage Pct
             * @description % of window days with valid retrievals
             */
            coverage_pct: number;
            /**
             * Satellite Ch4 Estimate
             * @description Satellite-derived CH4, tonnes/year (30-day temporal ensemble)
             */
            satellite_ch4_estimate: number;
            /**
             * Satellite Uncertainty Low
             * @description Lower bound of 95% confidence interval
             */
            satellite_uncertainty_low: number;
            /**
             * Satellite Uncertainty High
             * @description Upper bound of 95% confidence interval
             */
            satellite_uncertainty_high: number;
            /**
             * Reported Ch4
             * @description Corporate-reported Scope 1 CH4, tonnes/year
             */
            reported_ch4?: number | null;
            /**
             * Reported Source
             * @description Source document — ESG PDF filename or registry name
             */
            reported_source?: string | null;
            /** Reported Year */
            reported_year?: number | null;
            /**
             * Delta Pct
             * @description ((satellite − reported) / reported) × 100. Positive = under-reporting.
             */
            delta_pct?: number | null;
            /**
             * Sigma Deviation
             * @description Standard deviations by which satellite estimate exceeds reported value.
             */
            sigma_deviation?: number | null;
            /**
             * Evs
             * @description Emission Verification Score 0–100. 100 = perfect satellite/report alignment.
             */
            evs: number;
            flag: components["schemas"]["DiscrepancyFlag"];
            /**
             * Blockchain Tx Id
             * @description Hyperledger Fabric tx hash, set after anchoring
             */
            blockchain_tx_id?: string | null;
            /**
             * Report Id
             * @description Generated Granite verification report ID
             */
            report_id?: string | null;
        };
        /** FacilityListResponse */
        FacilityListResponse: {
            /** Facilities */
            facilities: components["schemas"]["FacilitySummary"][];
            /** Total */
            total: number;
        };
        /** FacilitySummary */
        FacilitySummary: {
            /** Facility Id */
            facility_id: string;
            /** Facility Name */
            facility_name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Sector */
            sector: string;
            /** Latest Evs */
            latest_evs?: number | null;
            latest_flag?: components["schemas"]["DiscrepancyFlag"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PlumeGeoJSONResponse */
        PlumeGeoJSONResponse: {
            /** Facility Id */
            facility_id: string;
            /**
             * Observation Date
             * Format: date
             */
            observation_date: string;
            /** Geojson */
            geojson: {
                [key: string]: unknown;
            };
            /**
             * Source
             * @default deterministic_demo_fixture
             */
            source: string;
            /**
             * Cached
             * @default true
             */
            cached: boolean;
        };
        /** PrototypeRunSummary */
        PrototypeRunSummary: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Facility Count
             * @default 0
             */
            facility_count: number;
            /**
             * Observation Start
             * Format: date
             */
            observation_start: string;
            /**
             * Observation End
             * Format: date
             */
            observation_end: string;
            /** Source */
            source: string;
            /** Task Id */
            task_id?: string | null;
            /** Error */
            error?: string | null;
        };
        /** PrototypeStatus */
        PrototypeStatus: {
            service_health: components["schemas"]["ServiceHealth"];
            credentials: components["schemas"]["CredentialStatus"];
            data: components["schemas"]["DataAvailability"];
            /**
             * Data Source
             * @enum {string}
             */
            data_source: "local" | "remote";
            /**
             * Granite Mode
             * @enum {string}
             */
            granite_mode: "cached" | "live";
            /**
             * Audit Mode
             * @enum {string}
             */
            audit_mode: "local_audit_fallback" | "live_fabric";
            latest_run?: components["schemas"]["PrototypeRunSummary"] | null;
            /** Missing Setup */
            missing_setup?: string[];
        };
        /** ReportRequest */
        ReportRequest: {
            /** Facility Id */
            facility_id: string;
            /**
             * Observation Start
             * Format: date
             */
            observation_start: string;
            /**
             * Observation End
             * Format: date
             */
            observation_end: string;
        };
        /** ReportResponse */
        ReportResponse: {
            /** Task Id */
            task_id: string;
            /**
             * Status
             * @default processing
             */
            status: string;
        };
        /** ReportResult */
        ReportResult: {
            /** Report Id */
            report_id: string;
            /** Facility Id */
            facility_id: string;
            /** Report Html */
            report_html: string;
            /** Blockchain Tx Id */
            blockchain_tx_id?: string | null;
            /** Audit Mode */
            audit_mode?: string | null;
            /**
             * Cached
             * @description True if served from Granite report cache (ADR-006)
             */
            cached: boolean;
        };
        /** ServiceHealth */
        ServiceHealth: {
            /** Backend */
            backend: boolean;
            /** Ml */
            ml: boolean;
        };
        /** TaskStatus */
        TaskStatus: {
            /** Task Id */
            task_id: string;
            /** Status */
            status: string;
            /** Progress Stage */
            progress_stage?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerificationRunRequest */
        VerificationRunRequest: {
            /** Facility Ids */
            facility_ids?: string[] | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Bbox
             * @description Bounding box [west, south, east, north].
             */
            bbox?: number[] | null;
            /**
             * Reuse Existing Raw Data
             * @default true
             */
            reuse_existing_raw_data: boolean;
        };
        /** VerificationRunResponse */
        VerificationRunResponse: {
            /** Task Id */
            task_id: string;
            /**
             * Status
             * @default processing
             */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_facilities_facilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityListResponse"];
                };
            };
        };
    };
    get_facility_detail_facilities__facility_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facility_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EVSScore"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_report_reports_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_esg_pdf_esg_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_esg_pdf_esg_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ESGUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_status_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plume_geojson_plume__facility_id__geojson_get: {
        parameters: {
            query: {
                observation_date: string;
            };
            header?: never;
            path: {
                facility_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlumeGeoJSONResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prototype_status_prototype_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrototypeStatus"];
                };
            };
        };
    };
    start_verification_run_verification_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificationRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
